version: '3.8'

services:
  user-db:
    image: mariadb:latest
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: user_db
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - user_data:/var/lib/mysql
      - ./user-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mariadb_network

  order-db:
    image: mariadb:latest
    container_name: order-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: order_db
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - order_data:/var/lib/mysql
      - ./order-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mariadb_network

  item-db:
    image: mariadb:latest
    container_name: item-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: item_db
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - item_data:/var/lib/mysql
      - ./item-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mariadb_network

volumes:
  user_data:
  order_data:
  item_data:

networks:
  mariadb_network:
    driver: bridge

