CREATE DATABASE IF NOT EXISTS `${ITEM_DATABASE}`;
USE `${ITEM_DATABASE}`;

CREATE USER IF NOT EXISTS '${USER}'@'%' IDENTIFIED BY '${PASSWORD}';
GRANT ALL PRIVILEGES ON `${ITEM_DATABASE}`.* TO '${USER}'@'%';
FLUSH PRIVILEGES;
