CREATE DATABASE IF NOT EXISTS `${ITEM_DATABASE}`;
USE `${ITEM_DATABASE}`;

-- CREATE TABLE IF NOT EXISTS `${ITEM_TABLE}` (
--     `quantity` int(11) NOT NULL,
--     `id` bigint(20) NOT NULL AUTO_INCREMENT,
--     `seller_id` bigint(20) DEFAULT NULL,
--     `description` varchar(255) DEFAULT NULL,
--     `name` varchar(255) DEFAULT NULL,
--     PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE USER IF NOT EXISTS '${USER}'@'%' IDENTIFIED BY '${PASSWORD}';
GRANT ALL PRIVILEGES ON `${ITEM_DATABASE}`.* TO '${USER}'@'%';
FLUSH PRIVILEGES;
