CREATE DATABASE IF NOT EXISTS `${USER_DATABASE}`;
USE `${USER_DATABASE}`;

CREATE USER IF NOT EXISTS '${USER}'@'%' IDENTIFIED BY '${PASSWORD}';
GRANT ALL PRIVILEGES ON `${USER_DATABASE}`.* TO '${USER}'@'%';
FLUSH PRIVILEGES;
